version: "3.8"

services:
  app:
    container_name: thumbnail-generator-api
    image: thumbnail-generator-api
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
