openapi: 3.0.0
tags:
  name: Thumbnail
  description: related endpoints.
paths:
  /thumbnail/uploadImage:
    post:
      summary: Upload an image to Cloudinary.
      description: Upload an image to Cloudinary and return the image URL.
      tags:
        - Thumbnail
      parameters:
        - name: base64
          description: Image to upload as a base64 encoded string.
          in: application/json
          required: true
          type: string
          schema:
            type: string
            example: base64 encoded image
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      message: 
                        type: string
                        example: Image uploaded successfully
                      public_id:
                        type: string
                        example: v1652813957
                      secure_url:
                        type: string
                        format: url
                        example: https://res.cloudinary.com/dev-demos/image/upload/v1652813957/samples/ecommerce/analog-classic.jpeg
  /thumbnail/{image_id}:
    get:
      summary: Thumbnails for an image id.
      description: Get thumbnails for an image id.
      tags:
        - Thumbnail
      parameters:
        - name: image_id
          description: Image ID
          in: path
          required: true
          schema:
            type: string
            example: enhiell4p4kozlpu0xqg
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  original:
                    type: object
                    properties:
                      bytes:
                        type: integer
                        example: 5242880
                      format:
                        type: string
                        example: jpeg
                      width:
                        type: integer
                        example: 1920
                      height:
                        type: integer
                        example: 1080
                      public_id:
                        type: string
                        example: enhiell4p4kozlpu0xqg
                      secure_url:
                        type: string
                        example: https://res.cloudinary.com/dev-demos/image/upload/v1653134416/enhiell4p4kozlpu0xqg.jpg
                  thumbnails:
                    type: array
                    items:
                      type: object
                      properties:
                        width:
                          type: integer
                          example: 400
                        height:
                          type: integer
                          example: 300
                        secure_url:
                          type: string
                          example: https://res.cloudinary.com/dev-demos/image/upload/c_thumb,h_300,q_100,w_400/enhiell4p4kozlpu0xqg
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Resource not found - enhiell4p4kozlpu0xqg
                  http_code:
                    type: integer
                    example: 404

    delete:
      summary: Delete image from Cloudinary.
      description: Delete an image from Cloudinary.
      tags:
        - Thumbnail
      parameters:
        - name: image_id
          description: Image ID.
          in: path
          required: true
          schema:
            type: string
            example: enhiell4p4kozlpu0xqg
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: ok